import io
import os
import sys

import bpy

repo = r"E:\SpaghettiKart"
fast64 = os.path.join(repo, "tools", "blender", "fast64")
glb = r"E:\MarioArt\Meshes\Meshy_AI_mario_kart_64_empty_k_0608203211_texture.glb"
out = os.path.join(repo, "src", "first_person_kart_mesh.inc.c")
blend_out = os.path.join(repo, "artifacts", "first-person-kart-screens", "meshy_kart_cleaned.blend")

sys.path.insert(0, os.path.dirname(fast64))
try:
    import fast64

    fast64.register()
    fast64_status = "registered"
except Exception as exc:
    fast64_status = f"failed: {type(exc).__name__}: {exc}"

bpy.ops.object.select_all(action="SELECT")
bpy.ops.object.delete()
bpy.ops.import_scene.gltf(filepath=glb)

obj = next(obj for obj in bpy.context.scene.objects if obj.type == "MESH")
bpy.context.view_layer.objects.active = obj
obj.select_set(True)
obj.name = "first_person_meshy_kart_body"
obj.data.name = "first_person_meshy_kart_body_mesh"

bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)
bpy.ops.object.mode_set(mode="EDIT")
bpy.ops.mesh.select_all(action="SELECT")
bpy.ops.mesh.remove_doubles(threshold=0.01)
bpy.ops.mesh.delete_loose()
bpy.ops.mesh.normals_make_consistent(inside=False)
bpy.ops.object.mode_set(mode="OBJECT")

triangulate = obj.modifiers.new("first_person_triangulate", "TRIANGULATE")
triangulate.quad_method = "BEAUTY"
triangulate.ngon_method = "BEAUTY"
decimate = obj.modifiers.new("first_person_decimate", "DECIMATE")
decimate.ratio = 0.18
decimate.use_collapse_triangulate = True
bpy.context.view_layer.objects.active = obj
bpy.ops.object.modifier_apply(modifier=triangulate.name)
bpy.ops.object.modifier_apply(modifier=decimate.name)

mesh = obj.data
mesh.update()
uv_layer = mesh.uv_layers.active

image = None
for mat in mesh.materials:
    if mat and mat.use_nodes:
        for node in mat.node_tree.nodes:
            if node.type == "TEX_IMAGE" and node.image and "BaseColor" in node.image.name:
                image = node.image
                break
    if image:
        break
if image is None:
    for mat in mesh.materials:
        if mat and mat.use_nodes:
            for node in mat.node_tree.nodes:
                if node.type == "TEX_IMAGE" and node.image:
                    image = node.image
                    break
        if image:
            break

if image is None:
    raise RuntimeError("No texture image found for Meshy material")

if not image.pixels:
    image.pack()

width, height = image.size
pixels = list(image.pixels)

def sample_image(uv):
    u = uv.x % 1.0
    v = uv.y % 1.0
    x = max(0, min(width - 1, int(u * (width - 1))))
    y = max(0, min(height - 1, int((1.0 - v) * (height - 1))))
    idx = (y * width + x) * 4
    r = int(max(0.0, min(1.0, pixels[idx])) * 255.0)
    g = int(max(0.0, min(1.0, pixels[idx + 1])) * 255.0)
    b = int(max(0.0, min(1.0, pixels[idx + 2])) * 255.0)
    return r, g, b, 255

def simple_color(r, g, b, a):
    # Push the Meshy baked texture toward MK64-readable broad colors.
    if r > 150 and g < 100 and b < 100:
        return 210, 24, 20, a
    if r < 80 and g < 80 and b < 80:
        return 18, 18, 20, a
    if abs(r - g) < 28 and abs(g - b) < 28 and r > 90:
        return 170, 170, 160, a
    if b > r + 25 and b > g + 20:
        return 45, 80, 210, a
    return r, g, b, a

# Blender sees glTF as X=width, Y=depth, Z=height.
# First-person kart local uses X=width, Y=up, Z=forward.
precision = 8.0
scale_macro = 0.125
forward_offset = 0.0
up_offset = -1.1

vertices = []
tri_count = 0
for poly in mesh.polygons:
    if len(poly.loop_indices) != 3:
        continue
    tri_count += 1
    for loop_index in poly.loop_indices:
        loop = mesh.loops[loop_index]
        co = mesh.vertices[loop.vertex_index].co
        uv = uv_layer.data[loop_index].uv if uv_layer else None
        color = simple_color(*sample_image(uv)) if uv else (210, 24, 20, 255)
        x = int(round(co.x * precision))
        y = int(round((co.z + up_offset) * precision))
        z = int(round((-co.y + forward_offset) * precision))
        vertices.append((x, y, z, *color))

with open(out, "w", encoding="utf-8", newline="\n") as f:
    f.write("/* Generated by artifacts/scripts/convert_meshy_with_blender.py. */\n")
    f.write(f"/* Fast64 addon link status: {fast64_status}. */\n")
    f.write(f"/* Cleaned in Blender, decimated to {tri_count} triangles, and stored at 8x coordinate precision. */\n\n")
    f.write(f"#define FP_MESHY_KART_BODY_SCALE {scale_macro}f\n")
    f.write(f"#define FP_MESHY_KART_BODY_TRIANGLE_COUNT {tri_count}\n\n")
    f.write("static Vtx sMeshyKartBodyVtx[] = {\n")
    for x, y, z, r, g, b, a in vertices:
        f.write(
            f"    {{{{ {{ {x}, {y}, {z} }}, 0, {{ 0, 0 }}, "
            f"{{ 0x{r:02X}, 0x{g:02X}, 0x{b:02X}, 0x{a:02X} }} }}}},\n"
        )
    f.write("};\n\n")
    f.write("static Gfx sMeshyKartBodyDl[] = {\n")
    tri_base = 0
    while tri_base < tri_count:
        chunk = min(10, tri_count - tri_base)
        vb = tri_base * 3
        f.write(f"    gsSPVertex(sMeshyKartBodyVtx + {vb}, {chunk * 3}, 0),\n")
        local = 0
        while local + 1 < chunk:
            a0 = local * 3
            a1 = (local + 1) * 3
            f.write(f"    gsSP2Triangles({a0}, {a0 + 1}, {a0 + 2}, 0, {a1}, {a1 + 1}, {a1 + 2}, 0),\n")
            local += 2
        if local < chunk:
            a0 = local * 3
            f.write(f"    gsSP1Triangle({a0}, {a0 + 1}, {a0 + 2}, 0),\n")
        tri_base += chunk
    f.write("    gsSPEndDisplayList(),\n")
    f.write("};\n")

bpy.ops.wm.save_as_mainfile(filepath=blend_out)
print(f"Fast64: {fast64_status}")
print(f"Wrote {out}")
print(f"Saved {blend_out}")
print(f"verts={len(mesh.vertices)} tris={tri_count} image={image.name} size={width}x{height}")
