import math
import os

import bpy

repo = r"E:\SpaghettiKart"
out = os.path.join(repo, "src", "first_person_kart_wheels.inc.c")

wheel_specs = [
    ("export_front_wheel_combined", "Front", "sFirstPersonKartFrontWheel"),
    ("export_rear_wheel_combined", "Rear", "sFirstPersonKartRearWheel"),
]

precision = 8.0
scale_macro = 0.125

def material_color(obj, material_index):
    if material_index < len(obj.data.materials):
        mat = obj.data.materials[material_index]
        if mat is not None:
            r, g, b, a = mat.diffuse_color
            return (
                int(max(0.0, min(1.0, r)) * 255.0),
                int(max(0.0, min(1.0, g)) * 255.0),
                int(max(0.0, min(1.0, b)) * 255.0),
                int(max(0.0, min(1.0, a)) * 255.0),
            )
    return (24, 24, 28, 255)

def export_object(obj_name, label, symbol):
    obj = bpy.data.objects.get(obj_name)
    if obj is None:
        raise RuntimeError(f"Missing object: {obj_name}")
    if obj.type != "MESH":
        raise RuntimeError(f"{obj_name} is not a mesh")

    bpy.ops.object.select_all(action="DESELECT")
    bpy.context.view_layer.objects.active = obj
    obj.select_set(True)

    for poly in obj.data.polygons:
        poly.use_smooth = True
    obj.data.update()

    depsgraph = bpy.context.evaluated_depsgraph_get()
    eval_obj = obj.evaluated_get(depsgraph)
    mesh = bpy.data.meshes.new_from_object(eval_obj, depsgraph=depsgraph)
    mesh.transform(obj.matrix_world)

    triangulated = bpy.data.objects.new(f"{obj_name}_tri_export", mesh)
    bpy.context.collection.objects.link(triangulated)
    bpy.context.view_layer.objects.active = triangulated
    triangulated.select_set(True)
    tri = triangulated.modifiers.new("triangulate_for_mk64", "TRIANGULATE")
    tri.quad_method = "BEAUTY"
    tri.ngon_method = "BEAUTY"
    bpy.ops.object.modifier_apply(modifier=tri.name)
    mesh = triangulated.data

    origin = obj.matrix_world.translation
    vertices = []
    tri_count = 0
    for poly in mesh.polygons:
        if len(poly.vertices) != 3:
            continue
        tri_count += 1
        color = material_color(obj, poly.material_index)
        for vertex_index in poly.vertices:
            co = mesh.vertices[vertex_index].co - origin
            # Blender scene uses X = axle/right, Y = kart forward, Z = up.
            # The first-person render matrix uses local X = right, Y = up, Z = forward.
            x = int(round(co.x * precision))
            y = int(round(co.z * precision))
            z = int(round(co.y * precision))
            vertices.append((x, y, z, *color))

    bpy.data.objects.remove(triangulated, do_unlink=True)

    return {
        "obj_name": obj_name,
        "label": label,
        "symbol": symbol,
        "tri_count": tri_count,
        "vertices": vertices,
    }

exports = [export_object(*spec) for spec in wheel_specs]
bpy.ops.wm.save_as_mainfile(filepath=bpy.data.filepath)

with open(out, "w", encoding="utf-8", newline="\n") as f:
    f.write("/* Generated by artifacts/scripts/export_first_person_wheels_from_blender.py. */\n")
    f.write("/* Wheel meshes are centered on their Blender object origins. */\n\n")
    f.write(f"#define FP_MESHY_KART_WHEEL_SCALE {scale_macro}f\n\n")
    for export in exports:
        f.write(f"#define FP_MESHY_KART_{export['label'].upper()}_WHEEL_TRIANGLE_COUNT {export['tri_count']}\n")
    f.write("\n")

    for export in exports:
        symbol = export["symbol"]
        f.write(f"static Vtx {symbol}Vtx[] = {{\n")
        for x, y, z, r, g, b, a in export["vertices"]:
            f.write(
                f"    {{{{ {{ {x}, {y}, {z} }}, 0, {{ 0, 0 }}, "
                f"{{ 0x{r:02X}, 0x{g:02X}, 0x{b:02X}, 0x{a:02X} }} }}}},\n"
            )
        f.write("};\n\n")

        f.write(f"static Gfx {symbol}Dl[] = {{\n")
        tri_base = 0
        while tri_base < export["tri_count"]:
            chunk = min(10, export["tri_count"] - tri_base)
            vb = tri_base * 3
            f.write(f"    gsSPVertex({symbol}Vtx + {vb}, {chunk * 3}, 0),\n")
            local = 0
            while local + 1 < chunk:
                a0 = local * 3
                a1 = (local + 1) * 3
                f.write(f"    gsSP2Triangles({a0}, {a0 + 1}, {a0 + 2}, 0, {a1}, {a1 + 1}, {a1 + 2}, 0),\n")
                local += 2
            if local < chunk:
                a0 = local * 3
                f.write(f"    gsSP1Triangle({a0}, {a0 + 1}, {a0 + 2}, 0),\n")
            tri_base += chunk
        f.write("    gsSPEndDisplayList(),\n")
        f.write("};\n\n")

for export in exports:
    print(f"{export['label']} wheel: {export['obj_name']} tris={export['tri_count']} verts={len(export['vertices'])}")
print(f"Wrote {out}")
