#!/usr/bin/env python3
import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CSV_PATH = ROOT / "src" / "data" / "kart_character_stats.csv"
OUT_PATH = ROOT / "src" / "data" / "kart_character_stats_generated.inc.c"

CHARACTER_COUNT = 8
ACCEL_COUNT = 10


def f(value):
    text = f"{float(value):.6g}"
    if "." not in text and "e" not in text.lower():
        text += ".0"
    return f"{text}f"


def main():
    with CSV_PATH.open(newline="") as csv_file:
        rows = sorted(csv.DictReader(csv_file), key=lambda row: int(row["character_id"]))

    if len(rows) != CHARACTER_COUNT:
        raise SystemExit(f"expected {CHARACTER_COUNT} rows in {CSV_PATH}, found {len(rows)}")
    for expected_id, row in enumerate(rows):
        if int(row["character_id"]) != expected_id:
            raise SystemExit(f"expected character_id {expected_id}, found {row['character_id']}")

    lines = [
        "/* Generated by tools/generate_kart_character_stats.py from src/data/kart_character_stats.csv. */",
        "const KartCharacterStats gKartCharacterStats[KART_CHARACTER_STATS_COUNT] = {",
    ]
    for row in rows:
        accel = ", ".join(f(row[f"accel_{i}"]) for i in range(1, ACCEL_COUNT + 1))
        lines.extend(
            [
                f"    // {row['character']}",
                "    {",
                f"        {int(row['character_id'])}, \"{row['character']}\", \"{row['weight_class']}\",",
                f"        {f(row['steering_spring_multiplier'])}, {f(row['torque_multiplier'])},",
                f"        {f(row['shift_ideal_rpm_min'])}, {f(row['shift_ideal_rpm_max'])}, {f(row['shift_over_rpm'])},",
                f"        {{ {f(row['top_speed_50cc'])}, {f(row['top_speed_100cc'])}, {f(row['top_speed_150cc'])}, {f(row['top_speed_extra'])}, {f(row['top_speed_battle'])} }},",
                f"        {f(row['kart_top_speed'])}, {f(row['bounding_box_size'])}, {f(row['handling'])},",
                f"        {f(row['turn_speed_reduction_0'])}, {f(row['turn_speed_reduction_1'])}, {f(row['triple_a_boost'])},",
                f"        {{ {accel} }},",
                "    },",
            ]
        )
    lines.append("};")
    OUT_PATH.write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
